### ISSUE TITLE
Error installing message-db to AWS RDS Aurora Postgres

### ISSUE THREAD

**Issue by bkbwese** [message-db/message-db#1]
I have an RDS instance that I am trying to install message-db on. I set Postgres environment variables necessary to connect to the RDS instance. I run into this problem when executing the installation script:

```
Creating Schema
- - -
» message_store schema
psql:/home/ubuntu/message-db/database/schema/message-store.sql:1: ERROR:  must be member of role "message_store"
```

Seems to be an Amazon RDS specific issue:
https://stackoverflow.com/questions/26684643/error-must-be-member-of-role-when-creating-schema-in-postgresql
> When using Amazon RDS the user issuing the CREATE DATABASE must be a member of the role that will be the owner of the database.

I will see if I can adjust the role SQL file to include a grant to the user creating the role. Wanted to let you guys know of that current incompatibility (assuming that I didn't make a mistake).

**Comment by bkbwese** [comment]
I was able to bypass the error I was getting with a grant statement that was described in the stackoverflow post linked above. I don't have a good solution for this (I'm not a database grant expert), but this was my work around that required hardcoding my username into the sql file:

```
diff --git a/database/roles/message-store.sql b/database/roles/message-store.sql
index 4dfb30f..c58a017 100644
--- a/database/roles/message-store.sql
+++ b/database/roles/message-store.sql
@@ -1,6 +1,7 @@
 DO $$
 BEGIN
   CREATE ROLE message_store WITH LOGIN;
+  GRANT message_store TO postgres;
 EXCEPTION
   WHEN duplicate_object THEN
       RAISE NOTICE 'The message_store role already exists';
```

If you guys know a way to grant the message_store role to the currently logged in user, that would mitigate this all together for any other people trying to deploy to RDS.

**Comment by sbellware** [comment]
Thanks for the report! I'm going to post this to the Eventide Slack immediately.

I don't think that we can really presume to make changes to a somebody else's user.

I've seen StackOverflow posts about detecting the current user. I'll look them up.

I think it should be doable with something like:

```bash
MESSAGE_DB_MODE=aws database/install.sh
```

And then add the current user to the role. At least that would make it an opt-in.

**Comment by sbellware** [comment]
@bkbwese Can you join the Eventide Slack? We're discussing possible remediations in the `development` channel. We can shorten the proof cycle if we're engaged in more real time. Self sign-up for the Slack org is at: https://eventide-project-slack.herokuapp.com

**Comment by sbellware** [comment]
@bkbwese This issue is resolve. The installation script has been updated. Version 1.1.0 does not have the problem you found.

I'm assuming that since you ran the installation just yesterday that your message store is not in production yet and that recreating it isn't a problem. But if you need to make just an incremental change, let me know and we can provide an update script.
