### ISSUE TITLE
message-db Dockerfile

### ISSUE THREAD

**Issue by phillipgajadhar** [message-db/message-db#11]
Request for message-db Dockerfile (and consequently, a Docker image) that performs initialization of database, tables, functions, etc. Resonance with official Docker PostgreSQL image (https://hub.docker.com/_/postgres) would be appreciated.

Feedback appreciated.

**Comment by ntl** [comment]
Are you requesting that a Dockerfile to be added to this project, or for one to be uploaded to https://hub.docker.com?

**Comment by sbellware** [comment]
Yep, good idea. It's not something that is really typical of the user community, so not something that anyone really has lying around. The typical developer experience is running Postgres directly on the host machine. But it's something that we should do. It's just not something that has bubbled to the top of the priorities list.

Problem is that a Docker image would be more of a distribution mechanism for Postgres. Installing the Message DB is really just an execution of a Bash script. So, we'd be maintaining something much larger than the Message DB organization (presently). I'm not sure I want to incur the support liability for such when the PostgreSQL org has already invested (and can maintain) the cycles for offering a Docker image.

I may be underestimating the difficultly of installing Postgres and running the Message DB install script though.

@ntl Is this something you're volunteering to own as a project principal?

**Comment by alexrudd** [comment]
@sbellware 

The official postgres docker image has support for arbitrary [initialization scripts](https://hub.docker.com/_/postgres/#:~:text=DB-,initialization%20scripts,-If). This is the hacky Dockerfile I setup for testing:

```Dockerfile
FROM postgres:13.2-alpine

# Fetch latest version of message-db
ADD https://github.com/message-db/message-db/archive/refs/tags/v1.2.6.tar.gz message-db.tar.gz
RUN mkdir -p /opt/message-db; tar -xvf message-db.tar.gz -C /opt/message-db --strip-components=1

# Create message-db init script
RUN mkdir -p /docker-entrypoint-initdb.d
RUN echo "#!/bin/bash" > /docker-entrypoint-initdb.d/init-message-db.sh
RUN echo "cd /opt/message-db/database/; ./install.sh" >> /docker-entrypoint-initdb.d/init-message-db.sh
```

Build and run:

```bash
docker build -t message-db .
docker run -p 5432:5432 -e POSTGRES_PASSWORD=password message-db
```

**Comment by stetsmando** [comment]
@alexrudd I like that this is self contained. I was having trouble getting something like this to work and it turns out that using the `postgres:alpine` image will fail when trying to install message-db. Seeing this helped me out big time. Thanks!
