### ISSUE TITLE
How to upgrade between minor versions of messagedb

### ISSUE THREAD

**Issue by dminnear** [message-db/message-db#13]
It looks like the old method of upgrading the schema (https://github.com/message-db/message-db/blob/master/database/update.sh) has been deprecated in favor of https://github.com/message-db/message-db/blob/master/database/update/1.0.0.sh. Unfortunately, the new update script directs us not to run it against a messagedb v1 database, so it's unclear how to update messagedb v1 database schemas between minor versions.

What is the intended method of updating from say v.1.1.0 to the latest v1.1.6?

**Comment by sbellware** [comment]
I don't believe that there are any physical changes to the definition of the database between v1.1.0 to v1.1.6. When there are no update scripts for a version, then the update should be just a matter of installing the new code.

Updates that don't require changes to the database definition are typically just corrections to utility scripts that come with Message DB.

**Comment by dminnear** [comment]
Thanks for the quick response! Makes sense, I'm closing this issue.
