### ISSUE TITLE
Replace DROP OWNED BY for better RDS support

### ISSUE THREAD

**Issue by sbellware** [message-db/message-db#15]
Per @mpareja, `DROP OWNED BY` is not supported on AWS RDS.

In the uninstall script, replace the statement with individual drops.

**Comment by sbellware** [comment]
Done

**Comment by mpareja** [comment]
@sbellware I've confirmed that removing this statement eliminates the `ERROR:  permission denied to drop objects` issue encountered on AWS RDS when uninstalling.
