### ISSUE TITLE
Please add git tags / releases

### ISSUE THREAD

**Issue by AlekSi** [message-db/message-db#3]

**Comment by sbellware** [comment]
Here's our feeling on this.

The entirely of the code produced by the organization that builds Message DB does not use tags or releases. We use consistent commit messages when a new version is published, for example: "Version is increased from 1.0.0 to 1.0.1". So, just as any tag is a commit, a commit is a commit as well, and the commits for version numbers can be acquired (if ever needed) from the Git  log.

We keep release information with the release artifacts, ie: the packages.

In the end we use Git more than GitHub. We eschew features of GitHub that create lock-in to GitHub. That includes GitHub releases.

That said, we might reconsider this policy in light of real, concrete user need if such arrises.

**Comment by sbellware** [comment]
Ok. Tags and releases are added: https://github.com/message-db/message-db/releases
