### ISSUE TITLE
Performance/benchmarks

### ISSUE THREAD

**Issue by cocowalla** [message-db/message-db#4]
First let me say this looks like a really interesting project!

It would be really useful to include some performance figures/benchmarks, either here or in the Message DB [docs](http://docs.eventide-project.org/user-guide/message-db/).

For example, a comparison against a single RabbitMQ instance, with varying message and batch sizes.

**Comment by sbellware** [comment]
A comparison to RabbitMQ, or any message broker or message queue, wouldn't be terribly edifying. A message broker is a fundamentally different technology than a message store, implying significant differences in implementation patterns.

It really wouldn't be recommended to try to use an event store or message store where a message broker is already in use.

A message store is organized around persistent, durable streams and categories of streams rather than topics. While streams and categories play the role that message queues traditionally play, the implied architecture of services that consume entity event streams and entity event categories is radically different than the transport of messages in the application integration scenarios that MQ technologies are purposed for.

That said, there are some very basic benchmark scripts included with Message DB: https://github.com/message-db/message-db/blob/master/database/benchmark.sh

There's no way to create a canonical measure of Postgres performance without controlling so many operational parameters that the benchmarks themselves would be largely non-representative of any but an infinitesimally-small number of specific operational scenarios.

So, rather than risk misconstruing any benchmark metrics, we provide that rudimentary benchmark script so that users can get a start on characterizing the performance of their own Postgres configuration and topology.

**Comment by cocowalla** [comment]
> It really wouldn't be recommended to try to use an event store or message store where a message broker is already in use.

I wasn't thinking "as well as", but more "could this work _instead_ of a broker when massive scale isn't required".

I totally get what you're saying about the number of knobs Postgres has, I just thought it might be useful to have even the roughest of ideas about throughput. I'll try the script you linked to.

**Comment by sbellware** [comment]
@cocowalla A message store can totally displace a message broker, but it would be more appropriate for an application that is already structured in a way that leverages streams and categories of streams than plain old queues and topics.

Most uses of message brokers are for _application integration_; just for firing messages around a network _between_ applications. A message store isn't typically inter-application glue. It's more akin to _core application storage_ (structured as messaging).

So, brokers are used between things that are disparate and remote, like two applications that were never conceived from the start to work together, hence the _integration_ distinction. A message store is used _within_ the _related_ services that make up a system.

A message store _can be_ used as an integration transport between disparate applications, but it's a technology that is less "ad hoc" than a broker, and requires coordination and cooperation between the teams using it. So, it depends more on the character of the people in the organization, and on the organization's culture, more than on technological considerations. At best, it's a gray area that can only be decided situationally.

So, that said, Message DB will have the same performance characteristics of anything running on Postgres. It's persistent messaging, and there's inevitably no options for non-persistent messaging. Its performance should be comparable to using RabbitMQ with its durable messaging turned on.

I would guess that Postgres has stronger consistency guarantees than RabbitMQ's persistence, and that could make RabbitMQ appear to be more performant, but I'm really just making suppositions on this point without hard data.

So, for me, it would be more a question of architecture than of technology. It depends more on fit-to-purpose than performance, especially given the amount of performance tuning options available to both RabbitMQ and Postgres.

**Comment by cocowalla** [comment]
Thanks for such a detailed response!

> A message store can totally displace a message broker, but it would be more appropriate for an application that is already structured in a way that leverages streams and categories of streams than plain old queues and topics.

Ah, so message-db would be more akin to Kafka, Amazon Kinesis or Azure Event Hubs, where you might have workers reading from a firehouse of events?

> I would guess that Postgres has stronger consistency guarantees than RabbitMQ's persistence, and that could make RabbitMQ appear to be more performant

You can choose to persist messages (using mnesia) or not with RabbitMQ, and also tweakable there are also consumer acks and publisher confirms. Like Postgres, rabbit has a *lot* of knobs and switches!

**Comment by sbellware** [comment]
Yes indeed, Message DB is more like Kafka than RabbitMQ - at least in how messages are consumed. It's more reminiscent of working with a database than a message transport

And even considering that RabbitMQ has durable messaging via Mnesia, and Mnesia is a good out of the box data store for Erlang, it's not entirely the same caliber of store as something like Postgres, and really isn't intended to be.

For example, when I worked at Rackspace, Mnesia was the weak link when we used it in the foundations of our cloud products and OpenStack, and was the principal reason that we were keeping our eyes on alternative AMQP implementations, like one undertaken by IBM in C. Mnesia was prone to corrupting at high message volume when a cloud server crashed. That was a number of years ago, so it might have improved in the meantime.

That said, I've never seen such issues with Postgres, or similar database products.

The big difference between message stores and transports like RabbitMQ is the eschewance of things like ACKs (and the subsequent deletion of messages), and subsequently the reliance on consumer logic for ensuring only-once processing.

In the end, ACK messages aren't guaranteed to be received, and the idempotence logic has to be implemented in the consumer either way. So, given that such logic needs to be implemented anyway, the ACKs are largely superfluous and require extra steps to interact with messages. The same is true of most transports that come from the time when queue products were based on having smarts built into the queue than built into the consumer.

The absence of ACKs also greatly simplifies the retrieval of messages in batches, and the staging of them in memory.

But there will always be a place and use cases for transport - especially in integration scenarios.

**Comment by cocowalla** [comment]
Thanks, I really appreciate these in-depth responses that have helped me to better understand where message-db can fit in!

**Comment by sbellware** [comment]
Sure thing! Drop in to the Eventide Slack if you want to talk more about architecture and details. We’re got a couple users who are doing significant data processing apps with Message DB: https://eventide-project-slack.herokuapp.com/.

**Comment by leonardorb** [comment]
@sbellware I learned a lot by reading this thread! Thanks for the amazing responses. I'm also very curious about `message-db` and was looking for some performance/benchmarking references. I'm sure a lot of people will do the same!

Maybe adding just a link to this thread or its transcription to the official docs will ease some curious minds, even though who is really curious will end up here. 😄

**Comment by sbellware** [comment]
@leonardorb We plan on compiling a number of articles from diverse content like this to publish on the docs site. As well, we'll move Message DB's docs to its own site and out from under Eventide's docs. So many, many things to do.
