### ISSUE TITLE
`write-test-message.sh` fails if `uuidgen` not installed

### ISSUE THREAD

**Issue by chukinas** [message-db/message-db#52]
I ran across this issue when setting up message-db in a docker container. I was building from an official postgres image (`postgres:15.3-alpine3.18`), which does not have the `uuidgen` command installed. 

Adding the command via the dockerfile was simple enough (`apk add uuidgen`), but it has me wondering if this requirement couldn't be more explicit. Some options: 
- check for `uuidgen` in the test script and exit with a clear error message
- add `uuidgen` to the [list of requirements](http://docs.eventide-project.org/setup/postgres.html#software-prerequisites)

Thoughts?

**Comment by sbellware** [comment]
Oh, that's unfortunate. This is the first time we've encountered a Linux distribution that doesn't already have a `uuidgen` installed.

Did the problem present itself when installing Message DB, or when trying to use it?

I've added a note on `uuidgen` availability to the list of requirements. 

Thanks!

**Comment by chukinas** [comment]
I noticed once I got the test step. But I also use `docker-compose` and so after adding `uuidgen` to my image, I tore it all down and built it from scratch, so I can't completely guarantee there aren't also issues with the earlier install step.

**Comment by chukinas** [comment]
Anyway, this was just an FYI. By all means, close this issue if you consider it dealt with. And thanks for the prompt reply!

**Comment by sbellware** [comment]
Ah! It's probably only an issue if you run the tests - which isn't something that a user would do just to install and use Message DB.

It's entirely opt-in choice for someone who intends to work on the Message DB code itself, and part of developer setup. So, it's out of bounds for user setup requirements.

I'm going to remove that note from the docs as its impertinent to users.
